### ISSUE TITLE
Add variables support

### ISSUE THREAD

**Issue by filipowm** [filipowm/home-assistant-config#1]
It should be possible to define default variables (not in secret way) like:

```yaml
variables:
   var1:
      value: somevalue
```
and then use it:
```yaml
- alias: 'Do something'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: sensor.some_sensor.set_state
    data:
      state: {{ variables.var1.state }}
```

Suggestion to use: https://github.com/rogro82/hass-variables
