### ISSUE TITLE
Add device tracking using home router (asuswrt-based)

### ISSUE THREAD

**Issue by filipowm** [filipowm/home-assistant-config#10]
Add device tracking using home router (asuswrt-based).

**Comment by filipowm** [comment]
Added secrets:

- router_host
- router_username
- router_password

SSH on port 22 must be enabled

Tracker configuration is following:
```yaml
- platform: asuswrt
  host: !secret router_host
  username: !secret router_username
  password: !secret router_password
```
